version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: examen_civa
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./SQL/script.sql:/docker-entrypoint-initdb.d/script.sql  # ✅ Ruta corregida

  backend:
    image: jhonnystr/footballer-backend
    container_name: backend_container
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/examen_civa?serverTimezone=America/Lima
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8090:8090"

volumes:
  mysql_data:
